service: python-serverless-template

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7

plugins:
  - serverless-offline
  - serverless-python-requirements

functions:
  app:
    handler: functions/hello/main.hello
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'