defaults: &defaults
  docker:
    - image: circleci/python:3.7
  working_directory: ~/repo

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: yarn
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules



workflows:
  version: 2
  validation:
    jobs:
      - build