defaults: &defaults
  docker:
    - image: circleci/python:3.7
  working_directory: ~/repo

checkout_steps: &checkout_steps
  - restore_cache: &checkout_restore_cache
      name: Restore source .git cache
      keys:
        - source-v1-{{ .Branch }}-{{ .Revision }}
        - source-v1-{{ .Branch }}-
        - source-v1-
  - checkout
  - save_cache: &checkout_save_cache
      name: Save source .git cache
      key: source-v1-{{ .Branch }}-{{ .Revision }}
      paths:
        - ".git"

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - restore_cache: *checkout_restore_cache
      - checkout
      - save_cache: *checkout_save_cache
      - restore_cache:
          key: vilelf-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: vilelf-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Run tests
          command: |
            pipenv shell
            nosetests

workflows:
  version: 2
  validation:
    jobs:
      - test